### ISSUE TITLE
Parsing issue when having template files including interpolated strings

### ISSUE THREAD

**Issue by etorreborre** [foundweekends/giter8#102]
Please try to `g8 etorreborre/etorreborre/specs2-scala-2.10.g8`.

You should have an error like:

```
action parse error; template context is [anonymous]
line 1:1: unexpected token: e1
    at org.antlr.stringtemplate.language.ActionParser.primaryExpr(ActionParser.java:813)
    at org.antlr.stringtemplate.language.ActionParser.expr(ActionParser.java:539)
    at org.antlr.stringtemplate.language.ActionParser.templatesExpr(ActionParser.java:222)
    at org.antlr.stringtemplate.language.ActionParser.action(ActionParser.java:126)
    at org.antlr.stringtemplate.StringTemplate.parseAction(StringTemplate.java:876)
    at org.antlr.stringtemplate.language.TemplateParser.action(TemplateParser.java:162)
    at org.antlr.stringtemplate.language.TemplateParser.template(TemplateParser.java:127)
    at org.antlr.stringtemplate.StringTemplate.breakTemplateIntoChunks(StringTemplate.java:850)
    at org.antlr.stringtemplate.StringTemplate.setTemplate(StringTemplate.java:441)
    at org.antlr.stringtemplate.StringTemplate.<init>(StringTemplate.java:308)
    at org.antlr.stringtemplate.StringTemplate.<init>(StringTemplate.java:293)
    at org.clapper.scalasti.adapter.ScalastiStringTemplate.<init>(ScalastiStringTemplate.java:57)
    at org.clapper.scalasti.StringTemplate.<init>(StringTemplate.scala:101)
...
```

**Comment by etorreborre** [comment]
I have another workaround. In the `default.properties` file define `dollar=$`. Then in your templates use `When("""^I retrieve the result""" + $dollar$)`.

**Comment by agemooij** [comment]
Did you test that? I just get an `unexpected char: '$'` error while it is parsing the `default.properties` file and asking questions.

**Comment by etorreborre** [comment]
That was definitely working for me but I haven't tried recently.

**Comment by argast** [comment]
You can use `$"$"$` combination to work around this problem.

e.g. in Scala:
`s"$var" -> s"$"$"$var"`

**Comment by vladap** [comment]
It gets quite ugly with javascript templates for AngularJs. As well as with Maven properties, checkstyle and scalastyle xmls.

Parser should forward look for a complete $var$ pattern where var can't have spaces, line breaks and any char which doesn't make sense in var name.

Without a fix it looks like dollar was an unfortunate choice for escaping, instead of {{ }}, <% %>, <? ?> whatever. Few places for placeholders  but potentially many for dollars in different contexts.

**Comment by vladap** [comment]
As well I would change title because it is more general problem than just with interpolated strings.

**Comment by foxmk** [comment]
I can change the behaviour of templating engine to fix this issue, but there 
are several possible solutions:
- Escape `$`: `\$` or `$$`. But this would not allow to develop template independently, which I would like to achieve.
- Restrict variable names to `[a-zA-Z_-]`, which can break some existing templates and, in some cases won't work (If template contains `println(s"$name_$foo")`, for example).

Personally I would prefer the second solution.

**Comment by eed3si9n** [comment]
With Pamflet I've always used `\$` to escape. I wonder if that's something specific to Pamflet, or if there's been some change to StringTemplate.

**Comment by eed3si9n** [comment]
`\$` works for me.
Maybe this is why I tagged this issue with Documentation.

**Comment by foxmk** [comment]
The problem with escaping is that for example, I want to develop template separately.

I create `my-template.g8/src/main/g8/src/main/$package$/Main.scala` and I want 
to create IDEA project inside `my-template.g8/src/main/g8` to be able to edit and compile it.

But if I want to write:

```scala
package $package$

object Main extends App {
  val foo = "foo"
  val bar = "bar"
  println(s"\$foo\$bar") // I need to escape this
}
```

inner project won't work properly. Same thing with `.gitignore` the `.idea` folder.

**Comment by eed3si9n** [comment]
@foxmk I think that's a whole different issue from what's being reported here. Eric reported "action parse error; template context is [anonymous]".

**Comment by djmittens** [comment]
Hi, i was recently also trying to use giter8 to create a template which has amongst other things, sh files which would provide example commands to start docker containers with the right parameters, and therefore have a lot of env vars defined with `$VAR` which break giter8, this is a pretty big issue for me, so getting a work around or something like that would be of huge help.

**Comment by Tvaroh** [comment]
`$"$"$` doesn't work anymore, other solutions above neither. It's pity to see such a child problems in a project like this.

**Comment by kknd22** [comment]
I think #3 is the **right** solution:        

> Look for existing properties and ignore unknown variables. But we should at least notify user about them.

It make no sense to pollute the whole source code with all kinds of escape while the ONLY replacements are limited to a very small set...

**Comment by laughedelic** [comment]
Escaping with `\$` works for me with sbt 0.13.15 which should be using Giter8 0.7.2

**Comment by metasim** [comment]
FWIW: I'm having this problem with sbt 0.13.16 `sbt-giter8` 0.9.0; can't figure out how to escape '$'

**Comment by djmittens** [comment]
It seems like there was an identified correct solution (eg. if there is no token specified in build.properties, then dont try to find the closing dollar) is it a difficult change?  and if so where would one look to make it?

**Comment by ryan-williams** [comment]
FWIW, I believe I'm seeing both `\$` and `$"$"$` working atm, SBT 1.1.0 and Giter8 0.11.0-M2

**Comment by salim7** [comment]
It would be great to have a more intelligent behavior, like auto-escaping for undefined vars or when a closing $ sign is missing.

**Comment by TonioGela** [comment]
> Hi, i was recently also trying to use giter8 to create a template which has amongst other things, sh files which would provide example commands to start docker containers with the right parameters, and therefore have a lot of env vars defined with `$VAR` which break giter8, this is a pretty big issue for me, so getting a work around or something like that would be of huge help.

I think that the [verbatim](http://www.foundweekends.org/giter8/Combined+Pages.html#verbatim+field) could solve here.

Since issue title is `Parsing issue when having template files including interpolated strings` and, like in the above example, escaping dollars like `\$` works perfectly with the current version `0.13.1` (see screenshots), I think the only thing left is adding this detail to the documentation. I'll write a PR asap.

![image](https://user-images.githubusercontent.com/41690956/118861838-4338a100-b8dd-11eb-8597-63108766f18d.png)
![image](https://user-images.githubusercontent.com/41690956/118861871-4b90dc00-b8dd-11eb-9812-97b18aba4a99.png)
