### ISSUE TITLE
Unable to install giter8; dependency missing in repo

### ISSUE THREAD

**Issue by dbarowy** [foundweekends/giter8#113]
If I run `cs n8han/giter8`, I get:

    Getting net.databinder.conscript conscript_2.9.2 0.4.1 ...

    :: problems summary ::
    :::: WARNINGS
    		module not found: net.databinder.conscript#conscript_2.9.2;0.4.1

	==== local: tried

	  /home/dan/.ivy2/local/net.databinder.conscript/conscript_2.9.2/0.4.1/ivys/ivy.xml

	==== sonatype-releases: tried

	  https://oss.sonatype.org/content/repositories/releases/net/databinder/conscript/conscript_2.9.2/0.4.1/conscript_2.9.2-0.4.1.pom

	==== Maven Central: tried

	  http://repo1.maven.org/maven2/net/databinder/conscript/conscript_2.9.2/0.4.1/conscript_2.9.2-0.4.1.pom

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: net.databinder.conscript#conscript_2.9.2;0.4.1: not found

		::::::::::::::::::::::::::::::::::::::::::::::

    :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
    unresolved dependency: net.databinder.conscript#conscript_2.9.2;0.4.1: not found
    Error during sbt execution: Error retrieving required libraries
      (see /home/dan/.conscript/boot/update.log for complete log)
    Error: Could not retrieve conscript 0.4.1

Navigating to `http://repo1.maven.org/maven2/net/databinder/conscript/conscript_2.9.2/` reveals that there is no `0.4.1` directory, only `0.4.2`.

**Comment by eed3si9n** [comment]
```
$ cs foundweekends/giter8
```

works for me.
