### ISSUE TITLE
No prompts are shown on Windows

### ISSUE THREAD

**Issue by jpsacha** [foundweekends/giter8#114]
No prompts are shown when using giter8 on Windows (7). For instance, after running:

```
g8 n8han/giter8
```

I see only

```
Creates a giter8 project template.
```

If I type something and press Enter, inputs are accepted and template is created. It is difficult to work with this way since you do not know what inputs you are supposed to provide.

**Comment by eed3si9n** [comment]
This is fixed in https://github.com/foundweekends/giter8/pull/124
