### ISSUE TITLE
Cannot install giter8

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [foundweekends/giter8#116]
If I issue this:
curl https://raw.github.com/n8han/conscript/master/setup.sh | sh

followed by:
~/bin/cs n8han/giter8

I get this error message:
An unexpected error occurred: Please check your internet connection.
And if you're using a pre-release version of Java, please try with
a final release version.
Exception message: https://api.github.com/repos/n8han/giter8/git/refs/heads/master

I'm really behing a proxy, but any other Java or 3rd party app works ok.
I have tweaked network.properties to use the environment variable https_proxy variable.

Please, any idea what can be wrong?

**Comment by dghant1024** [comment]
'cs foundweekends/giter8' worked for me.  Sorry for being three years late :-) 
https://github.com/foundweekends/conscript/issues/98

**Comment by DavidPerezIngeniero** [comment]
Thanks.  I close the issue, because after 3 years, I'm not using this any more.
