### ISSUE TITLE
Respect .gitignore (.DS_Store files should be ignored)

### ISSUE THREAD

**Issue by choffmeister** [foundweekends/giter8#123]
Hi guys,

it almost made me throw giter8 away... Sometimes, when I was thinking I had nothing changed to my custom giter8 template, I got

```
problem parsing template 'anonymous'
line 1:1: unexpected char: 0x0
    at org.antlr.stringtemplate.language.DefaultTemplateLexer.nextToken(DefaultTemplateLexer.java:149)
    at antlr.TokenBuffer.fill(TokenBuffer.java:69)
    at antlr.TokenBuffer.LA(TokenBuffer.java:80)
    at antlr.LLkParser.LA(LLkParser.java:52)
        ...
```

error when trying to create a project from my template. Because the error message is quiet useless, I could not find out what caused the error. Now I know: My mac created `.DS_Store` files, which where parsed by giter8. Those files (as well as `._.DS_Store` and `Thumbs.db`) should be ignore by default.
# How to cause the error
- Create a new template with `$ g8 n8han/giter8`
- Browse with the finder to the `src/main/g8` directory and make the finder create a .DS_Store file
- Test template locally with `$ g8 file://path/to/template.g8/ --name=uftest --force`
# Expectation
- No error should occur
# Solution
- Ignore files like `.DS_Store`, `._.DS_Store`, `Thumbs.db` (and maybe some others)

**Comment by phdoerfler** [comment]
Any estimate on when we might see this implemented? I also just ran into this issue and my reaction was similar to OP's.

**Comment by aafa** [comment]
+1 to get ignore rules from .gitignore 
that would simplify things a lot
