### ISSUE TITLE
Support defining formatting for file names on Windows

### ISSUE THREAD

**Issue by sslavic** [foundweekends/giter8#130]
Currently (giter8 0.6.2), it is not possible to define formatting for file names on Windows, since double quotes (surrounding format name in format specification) cannot be used in file name on Windows. List of that one and other reserved characters on Windows can be found [here](http://msdn.microsoft.com/en-us/library/aa365247%28VS.85%29)

E.g. in my template project, under directory named project I wanted to create a file named:

```
$name;format="Camel"$Build.scala
```

Creating

```
$name;format='Camel'$Build.scala
```

worked ok.

Consider replacing double quotes or for backward compatibility supporting also single quotes around format name. Even better, consider removing any characters wrapping around format name.

**Comment by tuhlmann** [comment]
@sslavic Would you mind pasting your workaround? 
We have this one template filename in our project and it's blocking me from testing on Windows?

Awesome thanks!

**Comment by tuhlmann** [comment]
As a future reference it works to add the formatting option after the name field using two underscores (`__`), like so:

```
$name__Camel$Build.scala
```

**Comment by TonioGela** [comment]
@sslavic or @eed3si9n I think this can be closed since the original issue was addressed since now you can use the syntax `$name__Camel$Build.scala`.
