### ISSUE TITLE
Unable to Install giter8 on Windows

### ISSUE THREAD

**Issue by pheath** [foundweekends/giter8#148]
I am running Java 7 (1.7.0_51), and I have conscript installed successfully.  However, the command to install giter8 is failing with the error below.  Please advise if you need additional information to resolve.

PS C:\Users\e63842\workspace> ..\bin\cs.bat n8han/giter8
Error: Unknown option --version
Error: Missing argument <template>
g8 0.6.6
Usage: giter8 [search] [options] <template>

Command: search
Search for templates on github
  <template>
        git or file URL, or github user/repo
  -b <value> | --branch <value>
        Resolve a template within a given branch
  -t <value> | --tag <value>
        Resolve a template within a given tag
  -f | --force
        Force overwrite of any existing files in output directory
  --paramname=paramvalue
        Set given parameter value and bypass interaction.

EXAMPLES

Apply a template from github
    g8 n8han/giter8

Apply using the git URL for the same template
    g8 git://github.com/n8han/giter8.git

Apply template from a remote branch
    g8 n8han/giter8 -b some-branch

Apply template from a remote tag
    g8 n8han/giter8 -t some-tag

Apply template from a local repo
    g8 file://path/to/the/repo

Apply given name parameter and use defaults for all others.
    g8 n8han/giter8 --name=template-test

Conscripted n8han/giter8 to C:\Users\e63842\bin\g8.bat
PS C:\Users\e63842\workspace>

**Comment by eed3si9n** [comment]
Sorry, this is actually the output of a *successful* installation. I know.
I opened #188 to improve this.
