### ISSUE TITLE
g8 command not recognized during install process-Ubuntu 14.04

### ISSUE THREAD

**Issue by ljconley** [foundweekends/giter8#162]
When I first attempted to install giter8 I got an error when running "g8" with no parameters saying that the command was not recognized. The most recent time i ran the install commands they worked with no problems and I am able to use g8 now, but I still need to learn more about why this error took place for professional reasons. Unfortunately I didn't keep logs of the terminal session. My operating system is ubuntu 14.04.

EDIT: this was the solution I was provided with by a more experienced coder. "it installs in the ~/bin directory and when .bashrc loads (when a shell is created) it adds ~/bin to the PATH if that folder exists, so only upon the next shell instance would it create that PATH entry".

**Comment by TonioGela** [comment]
This issue was related to how bash works and it's not really about giter8. IMHO it can be closed @eed3si9n. The alternative is to document that coursier can be used to install it and to refer to its documentation.
