### ISSUE TITLE
Is there a way to filter the latest maven dependency?

### ISSUE THREAD

**Issue by ssanj** [foundweekends/giter8#164]
To find the latest version of a dependency I can use the following in default.properties:

```
some_dep_version  = maven(groupId, artifactId)
```

Is there some way to get the latest version that is not a milestone release or a release candidate?

eg: 
The latest scalatest version is 1.4.RC2. I'd prefer to get 1.3 which is not a release candidate.
The latest scala version is 2.12.0-M1. I'd prefer to get 2.11.7 which is not a milestone release.

**Comment by xuwei-k** [comment]
There is no way in `0.6.8`. Pull requests welcome.

**Comment by ssanj** [comment]
This has been implemented in #275 and can be closed.

**Comment by TonioGela** [comment]
@xuwei-k this can be closed since awhile :P
