### ISSUE TITLE
Instructions to compile localy

### ISSUE THREAD

**Issue by rafael** [foundweekends/giter8#166]
Hi all -

Are there any instructions on how to compile giter8 from the source and produce the g8 binary?

**Comment by padilo** [comment]
Take a look at the wiki: https://github.com/foundweekends/giter8/wiki/Installing-local-version-of-giter8

**Comment by njlg** [comment]
For some reason conscript still tries to pull giter8 from the old namespace (net.databinder)

```
> cs --local foundweekends/giter8/0.6.9-SNAPSHOT
Getting net.databinder.giter8 giter8_2.10 0.6.9-SNAPSHOT ...
```
