### ISSUE TITLE
ls workaround: (was Creating new project: 500 exception)

### ISSUE THREAD

**Issue by JoyMonteiro** [foundweekends/giter8#170]
Hello,

I tried creating a new unfiltered project using the instructions in 
http://unfiltered.databinder.net/Try+Unfiltered.html

It always seems to die with a 500 exception.

I then tried 
g8 http://github.com/unfiltered/unfiltered-netty.g8

and it gave me a 301 "Moved Permanently" exception. I verified that that URL exists.

If I try 
g8 git://github.com/unfiltered/unfiltered-netty.g8

I again get a 500  Unexpected response error.

However,
g8 n8han/giter8 

works perfectly.

Any pointers as to what I'm doing wrong?

I also tried the variants
g8 softprops/unfiltered
g8 unfiltered/unfiltered-netty

as well, and again it fails with the 500 exception.

TIA,
Joy

**Comment by maxmithun** [comment]
I got a similar error while creating a project from template i have locally 

`Unexpected response status: 500`

When i disable my internet and try to create the project i came across that it is trying to connect to the URL `http://ls.implicit.ly/api/1/latest/giter8-plugin?user=n8han`

Accessing the URL through browser will return `Internal Server Error` which `HTTP response code 500`

**Comment by JoyMonteiro** [comment]
I'm getting a similar problem with local repos too, though the url is:
`http://ls.implicit.ly/api/1/latest/unfiltered?user=unfiltered`

Any workaround that you know of?

TIA,
Joy

**Comment by maxmithun** [comment]
I am not able to sort from where this URL is called :( or is there a way to disable checking for latest API

**Comment by ricsirigu** [comment]
I'm getting `Unexpected response status: 500` and I'm not able to download the template

**Comment by ricsirigu** [comment]
When I try `g8 joescii/lift-ng.g8` I get `Unexpected response status: 500` and I'm not able to download the template

**Comment by maxmithun** [comment]
@JoyMonteiro The parameter `giter8_version = ls(giter8-plugin, n8han)` in the default.properties file which was causing problem ( accessing  `http://ls.implicit.ly/api/1/latest/giter8-plugin?user=n8han` ) for me. i commented it out the property in my template and it worked fine 

can you check for the parameter `giter8_version = ls(unfiltered, unfiltered)` in template properties file.

**Comment by andersthorbeck** [comment]
I had the same issue, when trying to run 
```
$ g8 unfiltered/unfiltered
```

The workaround @maxmithun described worked for me as well. I cloned `https://github.com/unfiltered/unfiltered.g8` into a local repo, changed the value of the property `unfiltered_version` in file `src/main/g8/default.properties` from 
`unfiltered_version = ls(unfiltered, unfiltered)` to `unfiltered_version = 0.8.4`.

Then I could run `g8` like so
```
$ g8 file:///path/to/local/unfiltered.g8
```
without problem.

**Comment by xuwei-k** [comment]
- https://github.com/foundweekends/giter8/issues/179
- https://github.com/softprops/ls/issues/76

**Comment by eed3si9n** [comment]
We should catch `ls(...)`, warn the user, and let them enter the version number manually.

**Comment by foxmk** [comment]
Should we close the issue, since we are not using implicit.ly anymore?

**Comment by softprops** [comment]
+1

**Comment by eed3si9n** [comment]
We might need to still warn the user if it's used in a template.
