### ISSUE TITLE
Is giter8 still alive?

### ISSUE THREAD

**Issue by padilo** [foundweekends/giter8#174]
We are really interested in having this PR #169, and I see that this project is quite abandoned...

If it's not going to have any maintainers or someone who can review and merge PRs it's quite useless. Maybe we should fork it to have just at least a way to correct bugs and add additional features to it.

What do you think?

**Comment by laughedelic** [comment]
:up:

**Comment by aafa** [comment]
+1

**Comment by mhotan** [comment]
+1.  In the case where no one feels up to taking on the maintenance and evolution of the project, does anyone know of an alternative?

**Comment by xuwei-k** [comment]
- https://twitter.com/eed3si9n/status/718906550568534018
- https://twitter.com/eed3si9n/status/718907349830864897

**Comment by padilo** [comment]
Awesome, can I join to the party? I don't know If I would have enough time, but I'll try to do my best

**Comment by eed3si9n** [comment]
@padilo Invited :)

**Comment by aafa** [comment]
Sounds great, I would love to join!
