### ISSUE TITLE
giter8 alternative?

### ISSUE THREAD

**Issue by mhotan** [foundweekends/giter8#175]
As addressed in #174, Giter8 appears to be flat lined and in the event that it is declared as no longer maintained does anyone know of a viable alternative?

**Comment by ches** [comment]
As noted on #174:

- https://twitter.com/eed3si9n/status/718906550568534018
- https://twitter.com/eed3si9n/status/718907349830864897

As for alternatives if you're still looking, I don't know of any implemented in Scala. There are a few [Yeoman](http://yeoman.io/) templates out there for Scala projects and in general it is a tool that generates project skeletons.
