### ISSUE TITLE
delete ls integration?

### ISSUE THREAD

**Issue by xuwei-k** [foundweekends/giter8#179]
ls.implicit.ly is no longer alive?

ref https://github.com/softprops/ls/issues/76, https://github.com/foundweekends/giter8/pull/178, https://twitter.com/n8han/status/692719614711717888

**Comment by xuwei-k** [comment]
also `repo.lessis.me` is dead?

https://github.com/foundweekends/giter8/blob/d4a7a331be311371838e5bc3399294211d597e90/project/plugins.sbt#L2
https://travis-ci.org/foundweekends/giter8#L297

```
[warn] Host repo.lessis.me not found. url=http://repo.lessis.me/org/sonatype/oss/oss-parent/5/oss-parent-5.jar
[info] You probably access the destination server through a proxy server that is not well configured.
```

**Comment by eed3si9n** [comment]
If someone wants to try they can integrate directly with Maven repo by borrowing the code from https://github.com/rtimush/sbt-updates to read metadata from `maven-metadata.xml`, and sort the versions.

**Comment by xuwei-k** [comment]
> If someone wants to try they can integrate directly with Maven repo by borrowing the code from https://github.com/rtimush/sbt-updates to read metadata from maven-metadata.xml, and sort the versions.

:+1: 


- https://github.com/foundweekends/giter8/pull/136 
- https://twitter.com/xuwei_k/status/468770079388086272

**Comment by eed3si9n** [comment]
nice, I didn't know this was already part of giter8.

**Comment by xuwei-k** [comment]
But my implementations is not enough. I need more features like ivy https://ant.apache.org/ivy/history/2.3.0/ivyfile/dependency.html#revision

**Comment by softprops** [comment]
Heyo. I'm partially to blame here. I don't really maintain the ls-* family of things anymore. If you guys want to take them over you can. Otherwise, it may be a good idea to cut off support here.

**Comment by eed3si9n** [comment]
Done in c7ec7fca933b5ce4f548963a4093d7cef5fd1d73
