### ISSUE TITLE
update or remove scaffold sample

### ISSUE THREAD

**Issue by xuwei-k** [foundweekends/giter8#182]
- `scaffold sample` use play 2.0 ! it's tooooooooooo old :fearful:
  - https://github.com/foundweekends/giter8/blob/977b9230/sample/project/plugins.sbt#L8
  - https://github.com/foundweekends/giter8/blob/977b9230/sample/project/build.properties#L1
- play 2.0 use sbt 0.11.3. but latest `giter8-scaffold` plugin published only for sbt 0.13.x
  - http://repo1.maven.org/maven2/net/databinder/giter8/giter8-scaffold_2.9.1_0.12/
  - http://repo1.maven.org/maven2/net/databinder/giter8/giter8-scaffold_2.10_0.13/

I think we should create scripted tests for scaffold plugin in `scaffold/src/sbt-test` if possible. (and then remove sample?)

**Comment by ches** [comment]
I agree it would be nice to do both, add scripted tests and update/keep the sample. Many people don't understand scripted very well (after all this time I think @eed3si9n's blog post remains the best documentation on using it for sbt plugins…), so IMO it's good to keep a sample that people can understand more quickly.

I'll try to help with updating it when I can spare some time.

**Comment by foxmk** [comment]
I've added some testable examples in https://github.com/foundweekends/giter8/pull/261. Each example test case should contain template folder and reference output folder. Integration tests will ensure that rendered template contains the same content as reference output. It is easy to understand and use. Maybe we should stick with them?
