### ISSUE TITLE
license change to Apache-2.0

### ISSUE THREAD

**Issue by eed3si9n** [foundweekends/giter8#194]
Short version:
Hi giter8 contributors! Can I get your ok on changing the license to Apache-2.0? Please comment "yes, I approve" or "no".

@hadesgames, @peutetre, @keshin, @pk11, @jto

yes:
@xuwei-k, @softprops, @joescii, @thirstycrow, @ches, @butlermh, @pvlugter, @njlg, @KirinDave, @jberkel, @tlockney

Long version:
For wider adoption of giter8, I think it would help if we can switch the license from LGPL to Apache-2.0. I've gotten ok from Nathan (@n8han) but there are a dozen more contributors who has contributed 10 lines or more. I'm not sure how fast we can get everyone's ok, but if we can pull off the switch, I think it would be great.

**Comment by njlg** [comment]
Yes, I approve.

**Comment by jberkel** [comment]
Yes, I approve.

**Comment by xuwei-k** [comment]
Yes, I approve.

**Comment by tlockney** [comment]
Yes, I approve.

**Comment by ches** [comment]
Yes, I approve!

**Comment by butlermh** [comment]
Yes I approve.

Thank you!

Mark

**Comment by joescii** [comment]
Not a problem Eugene!

Thanks,
Joe

**Comment by softprops** [comment]
Yes, I approve

**Comment by pvlugter** [comment]
Yes, I approve

**Comment by eed3si9n** [comment]
got an ok in email from KirinDave and thirstycrow

**Comment by eed3si9n** [comment]
It didn't show up on https://github.com/foundweekends/giter8/graphs/contributors, but there are many commits from @jto. Can I get your ok?

**Comment by jto** [comment]
Yes, I approve

**Comment by eed3si9n** [comment]
Thanks everyone!

**Comment by hadesgames** [comment]
Yes, I approve
