### ISSUE TITLE
installation instructions don't quite work

### ISSUE THREAD

**Issue by tpolecat** [foundweekends/giter8#227]
Most people are probably using this from sbt now so it may not matter, but for me the installation instructions do nothing.

```
~$ curl https://raw.githubusercontent.com/foundweekends/conscript/master/setup.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1693  100  1693    0     0   7778      0 --:--:-- --:--:-- --:--:--  7766
~$ 
```

This is on MacOS Sierra 10.12 (16A323) with the default Terminal app and nothing fancy.

If I save the script to a file and execute it, it complains about not having `wget` (which is slightly funny since we have already established that `curl` is available). I stopped there.

**Comment by ssanj** [comment]
I also found the installation instructions did not work for me on MacOS (while it used to in the past). It's relatively painless to install if you have homebrew installed though:

```
brew install giter8
```

**Comment by TonioGela** [comment]
@tpolecat the documentation was recently updated and now the [Setup](http://www.foundweekends.org/giter8/setup.html) page contains manual and coursier based installation instructions.

**Comment by TonioGela** [comment]
@eed3si9n I think it can be closed.
