### ISSUE TITLE
terminal messed up with sbt new (at least)

### ISSUE THREAD

**Issue by tpolecat** [foundweekends/giter8#228]
Ok so I'm on `sbt-extras` for 0.13.13, JDK 8, MacOS default Terminal app. When I do `sbt new` I see the template title and then output stops.

```
~$ sbt new scala/scala-seed.g8
[info] Loading global plugins from /Users/rnorris/.sbt/0.13/plugins
[info] Set current project to rnorris (in build file:/Users/rnorris/)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Minimum Scala build.
```

If I then hit Enter it looks like this:

```
~$ sbt new scala/scala-seed.g8
[info] Loading global plugins from /Users/rnorris/.sbt/0.13/plugins
[info] Set current project to rnorris (in build file:/Users/rnorris/)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Minimum Scala build.

name [My Something Project]:
Template applied in ./my-something-project
~$
```

So there is something messed up with echo … I verified that I have the right version of JLine in `~/.sbt/boot`.

**Comment by tpolecat** [comment]
Same behavior with iTerm, fwiw.

**Comment by charafau** [comment]
I use standard sbt with iterm2, zsh and jdk8 and it works for me. Don't know what `sbt-extras` is doing but maybe that's the case?

**Comment by tlockney** [comment]
For what it's worth, I just tried this with `sbt-extras` and it worked fine for me in both iterm and terminal. Java version is:

```sh
~→ java -fullversion
java full version "1.8.0_66-b17"
```

**Comment by paulp** [comment]
I bet you have a .sbtignore which is trying to process the output of `sbt new` line by line and echoing selectively as it goes, but hangs up on the interactive questions sbt poses since such things didn't exist when the filter was written.

Since I just now ran into the same problem writing [a less messy sbt-new](https://gist.github.com/paulp/ba9bd0b5808a808c67cbd2bb9db08005).

**Comment by tpolecat** [comment]
@paulp that's it. 👍
