### ISSUE TITLE
wiki update

### ISSUE THREAD

**Issue by lewismj** [foundweekends/giter8#231]
Hi,

Sorry to be a pain, not sure how to create a PR for a wiki page. I was hoping one of the owners may do me a favour and add in the following to the end of giter8-templates.md (I just created an SBT template for multi-module + app). Or, if someone knows how to create a PR for the wiki please let me know.

| [lewismj/sbt-template.g8](https://github.com/lewismj/sbt-template.g8) | Multi-module project with application |

**Comment by laughedelic** [comment]
I think you can just edit the page directly: there is a button `Edit` in the right upper corner.

**Comment by lewismj** [comment]
Thanks for letting me know, just edited it.
