### ISSUE TITLE
Install giter8 in offline mode

### ISSUE THREAD

**Issue by hugomau** [foundweekends/giter8#238]
Hi, 

I have installed giter8 following these instructions http://www.foundweekends.org/giter8/setup.html and everything works but we really need to support offline installation.

My question is, having the necessary packages, how can we install and configure giter8 offline? Are there any instruction available for this?

Thank you.

I am working on Centos 7.3.

Thank you, 

Hugo

**Comment by TonioGela** [comment]
@hugomau the [Setup](http://www.foundweekends.org/giter8/setup.html) page contains the installation instructions. The [Manual](http://www.foundweekends.org/giter8/setup.html#Manual) section in particular asks you to `curl` a file whose name begins with  `giter8-bootstrap`

That file should have been build with [Coursier bootstrap](https://get-coursier.io/docs/cli-bootstrap), in particular using the [standalone](https://get-coursier.io/docs/cli-bootstrap.html#standalone-bootstraps) command-line argument, so as the documentation states:
```
[...] instead of loading URLs via the coursier cache, the tiny startup Java application 
loads JARs from this list via its own resources. That makes these standalone 
bootstrap runnable even with no network connection and an empty coursier cache.
```

**Comment by hugomau** [comment]
Hello Tonio,

I made this question in 2016, four and a half years ago. I don't remember why I did this question or what is giter8. I'm not even on the same job I was in 2016.

Some lessons to be learn from this.

Thank you for the feedback, anyway.

Best regards,

Hugo
