### ISSUE TITLE
Private repository is not matched

### ISSUE THREAD

**Issue by megri** [foundweekends/giter8#241]
When I run `g8 myorganization/myprivaterepo.g8` I get an unhandled exception:

```
org.eclipse.jgit.api.errors.TransportException: git://github.com/myorganization/myprivaterepo.g8.git:
  Repository not found.
```

I have a potential fix but I'm not sure how to test this locally or write a test case for it: https://github.com/megri/giter8/commit/c7750ee12f88dc70c7a559abf603ad260e6d3351

How do I proceed?

**Comment by eed3si9n** [comment]
You can publish Giter8 locally with a snapshot version and install it via Conscript.

**Comment by analytically** [comment]
Hi @eed3si9n, mind explaining this a bit more? We're running into this issue as well using `sbt new ...`, thanks!

**Comment by patrick-premont** [comment]
I've tested the proposed fix above, and it works for me but only if the condition `if e.getMessage == "Repository not found."` is removed. I think it is best to omit the message check.

So the fix simply changes the matched exception type, from `org.eclipse.jgit.api.errors.JGitInternalException` to`org.eclipse.jgit.api.errors.TransportException`.

I have not encountered an occurence of an `org.eclipse.jgit.api.errors.JGitInternalException`, but that check might have been introduced for a reason, so it may be worth accepting both types of exception?

**Comment by patrick-premont** [comment]
Make sense. Submitted PR #248

**Comment by eed3si9n** [comment]
Thanks!

For others following this case, *this issue was expedited via the Lightbend subscription.*

**Comment by megri** [comment]
Great to hear :)

**Comment by eed3si9n** [comment]
Fixed by https://github.com/foundweekends/giter8/pull/248
