### ISSUE TITLE
how to exclude folder ?

### ISSUE THREAD

**Issue by chandu0101** [foundweekends/giter8#246]
Hi 
in my template i have bunch of `non scala folders` , is it possible to exclude them from g8 processing ?

**Comment by lachatak** [comment]
From giter8's point of view they are just files/directories. Doesn't really care if it is scala or not. It has templated variable then it will be processed.

**Comment by chandu0101** [comment]
cool, then i don't care about giter8 for that project.

**Comment by lachatak** [comment]
I suppose it is relatively easy to delete not required folders after the generation :)
I am not a giter8 expert at all. This was my opinion.
