### ISSUE TITLE
multimodule support in one g8 git repository

### ISSUE THREAD

**Issue by lachatak** [foundweekends/giter8#268]
Hi,

We have a scenario  where we would like to have 1 single repository in the git with "submodules" containing different templates. The only possible way how we can do this now is to clone the project directly then use g8 with "g8 file://" to point to a submodule directory.
It would be good to be able to provide a directory after the git repo url which would force g8 to use a subdirectory for the template source.

/template-project
       /scalatemplate
              /src/main/g8
       /nodetemplate
              /src/main/g8

g8 git@github.com:user/template-project.g8.git -d scalatemplate
g8 git@github.com:user/template-project.g8.git -d nodetemplate

We would like to keep every template under the same repository.
What do you think?
Krisztian

**Comment by lachatak** [comment]
has been merged.
when do you think it could be released?

**Comment by eed3si9n** [comment]
I'm busy this week on conference. Probably after next week.

**Comment by lachatak** [comment]
@eed3si9n thank you your feedback!
Have a good conference!
k

**Comment by foxmk** [comment]
Closing the issue since #269 is merged
