### ISSUE TITLE
Release new version of giter8

### ISSUE THREAD

**Issue by lachatak** [foundweekends/giter8#276]
update brew as well :)

**Comment by lachatak** [comment]
When do you think it happen?:)

**Comment by eed3si9n** [comment]
Sorry I was waiting on https://github.com/foundweekends/giter8/pull/277.
Now that's merged we might be good to go. @foxmk?

**Comment by foxmk** [comment]
Yes, I think we can make a release. There are breaking changes in library interface though, so we should put it in changelist. And, probably, increment major version.

**Comment by lachatak** [comment]
How it goes?

**Comment by xuwei-k** [comment]
revert https://github.com/foundweekends/giter8/pull/281 or wait Scala 2.11.10 ?

https://github.com/scala/scala/pull/5664#issuecomment-291163434

**Comment by eed3si9n** [comment]
Also see #282. There seems to be a few regressions that was introduced.

**Comment by DWvanGeest** [comment]
Once those regressions are fixed, am very eager to get my hands on a new release (mostly for #259).

**Comment by eed3si9n** [comment]
It's out! https://github.com/foundweekends/giter8/releases/tag/v0.8.0

**Comment by lachatak** [comment]
👍
