### ISSUE TITLE
Maven 'stable' feature may be broken

### ISSUE THREAD

**Issue by bneil** [foundweekends/giter8#286]
After the latest release, I attempted to use the maven 'stable' feature in a g8 template, through the following command:
`sbt -sbt-version 0.13.13 new bneil/http4s.g8`

resulted in:

```
name [http4s quickstart]: 
organization [com.example]: 
package [com.example.tmp]: 
scala_version [2.12.1]: 
http4s_version [maven(org.http4s, http4s-blaze-server_2.12, stable)]:
```

Did I miss an implementation detail?

`default.properties`:
```
name = http4s quickstart
organization = com.example
package = $organization$.$name;format="norm,word"$

scala_version = maven(org.scala-lang, scala-dist)

http4s_version = maven(org.http4s, http4s-blaze-server_2.12, stable)
```

**Comment by eed3si9n** [comment]
sbt new uses Giter8 0.7.2 - https://github.com/sbt/sbt-giter8-resolver/blob/v0.1.3/project/Dependencies.scala#L6

**Comment by bneil** [comment]
Ah, my mistake - thanks for taking the time to review my issue
