### ISSUE TITLE
Include `https` as fallback protocol when accessing github.

### ISSUE THREAD

**Issue by ignasi35** [foundweekends/giter8#287]
`g8` defaults to GitHub when provided a repo of formant `user/repo.g8`. When accessing Github repositories, `g8` will use `git:` protocol by default and will fallback to `ssh:` (aka git@) if `git:` fails. See [this](https://github.com/foundweekends/giter8/blob/0edcc3540de4e59b0ba08fbac40b42da30427c38/library/src/main/scala/giter8/GitRepository.scala#L33-L34) and [this](https://github.com/foundweekends/giter8/blob/0edcc3540de4e59b0ba08fbac40b42da30427c38/library/src/main/scala/giter8/Git.scala#L47-L47).

In some corporate networks (or other limited scenarios) using ports 22 or 9418 is forbidden but 443 is not. I't be useful if `g8` would fallback to http://github.com/user/repo.g8.git as a last resort.

off-topic: Considering ubiquity of https and [security concerns](https://gist.github.com/grawity/4392747#protocols-to-choose-from-when-cloning), it might be useful to use `https` as the default protocol and default to `ssh:` or `git:` (in this order).

**Comment by Mogztter** [comment]
> In some corporate networks (or other limited scenarios) using ports 22 or 9418 is forbidden but 443 is not. I't be useful if g8 would fallback to http://github.com/user/repo.g8.git as a last resort.

I'm in the same boat!
@ignasi35 Did you find a work around ?

**Comment by ignasi35** [comment]
Hi @Mogztter , in lagom we're using a workaround (that I think will change in future versions of `sbt`):

```
sbt -Dsbt.version=0.13.15 new https://github.com/lagom/lagom-java.g8
```

HTH
