### ISSUE TITLE
Support applying templates from a custom tag or branch

### ISSUE THREAD

**Issue by jroper** [foundweekends/giter8#289]
It would be nice to be able to do something like this:

```
sbt new "lagom/lagom-java.g8#1.2.x"
```

Where the `#1.2.x` means use the `1.2.x` branch of the repository.  This has many use cases, such as:

* Being able to maintain templates for creating projects for older releases of some software (eg, the above)
* Being able to maintain templates for creating projects for development releases of some software
* Being able to easily test pull requests to a template (eg, `sbt new "somecontributor/lagom-java.g8#patch-1"`) before accepting them

**Comment by fabriziofortino** [comment]
This seems to be already supported by`-t`parameter.
https://github.com/foundweekends/giter8/blob/0.8.x/app/src/main/scala/giter8/Giter8.scala#L117

**Comment by palmerabollo** [comment]
@jroper use `-b` for branches (or `-t` for tags, as suggested by Fabrizio)

```
g8 0.7.2
Usage: giter8 [options] <template>

  <template>            git or file URL, or github user/repo
  -b, --branch <value>  Resolve a template within a given branch
  ...

EXAMPLES
...
Apply template from a remote branch
    g8 foundweekends/giter8 -b some-branch
```

Feel free to close this issue if it worked.
