### ISSUE TITLE
`.g8` postfix sounds very bad in Chinese

### ISSUE THREAD

**Issue by hepin1989** [foundweekends/giter8#295]
Hi, guys, thanks for this project first.

But I have to say, the `g8` sounds very bad to Chinese people.

Most people don't care `g` or `j`, and the `8` means `八` and sounds like `ba`.

When those two characters comes together, as `g8`, it sounds like `jiba` which mostly 
refs to `鸡巴`, means `dick` as slang in English.

So for me, and maybe most Chinese people, it's a very bad postfix.

As every time I read `xxxx-seed.g8`, I read `xxxx-seed.dick`.

BTW，No offense.

**Comment by eed3si9n** [comment]
鸡 as in chicken? I honestly don't know if we can do much about it at this point.
We are not likely going to change hundreds of community-controlled repositories.
Someone else also said sbt could mean 死变态.

**Comment by hepin1989** [comment]
@eed3si9n is not chicken when it with `巴`, I have to say, it must not be a problem in Japanese.
