### ISSUE TITLE
Order of parameters is not preserved in 0.8

### ISSUE THREAD

**Issue by imarios** [foundweekends/giter8#298]
To the best of my knowledge, if we had a default.properties file with fields:
```
b = 1
g = 2
a = $g$
```

when you run the template it should ask for the fields in the the same order {b, g, a}. Currently this is not the case. The order is quite random or maybe it orders the fields alphanumerically. 

In addition, I remember you could change the default value of a field using the fields added just before. So in this example above, if the user added 10 to `g`, then the suggestion for `a` would have changed to 10. This is not happening any more. I believe this also has to do with the order not being preserved.

This is probably a regression for 0.8?

**Comment by ssanj** [comment]
I can confirm that the order of fields requested does not follow that in default.properties in 0.8.

**Comment by eed3si9n** [comment]
This is "fixed" in 0.9.x branch by rolling back 0.8.0 changes.
