### ISSUE TITLE
cross build for sbt 1.0

### ISSUE THREAD

**Issue by xuwei-k** [foundweekends/giter8#318]

**Comment by MasseGuillaume** [comment]
Hey, anyone working on this task? Can I help out?

**Comment by eed3si9n** [comment]
@MasseGuillaume AFAIK no one is working on this, so you're welcome to stake the claim and send us a PR.

**Comment by MasseGuillaume** [comment]
@eed3si9n awesome, I'm on it,

**Comment by xuwei-k** [comment]
0.11.0-M2 released
- https://bintray.com/sbt/sbt-plugin-releases/sbt-giter8/0.11.0-M2#
- https://oss.sonatype.org/content/repositories/releases/org/foundweekends/giter8/giter8_2.12/0.11.0-M2/
- https://github.com/foundweekends/giter8/tree/v0.11.0-M2
