### ISSUE TITLE
CLI Won't Generate from Private Remote Repository with ssh config

### ISSUE THREAD

**Issue by tdrozdowski** [foundweekends/giter8#326]
If you have a config file in ~/$USER_HOME/.ssh - the g8 command line will not work properly.

Expected behavior - it would identify the proper key via the config and use that to login via ssh to GitHub 

Actual behavior - authentication fails and you are asked for username and password - which never work.

The only work around I currently have is to checkout the giter8 template projects locally and then use the file:// url to get to them.  Ideally this should 'just work'.

OS: Mac OS X 10.12.6
Giter8 - 0.9.0 (via brew)

**Comment by taraspogrebniak** [comment]
I have the same problem when try to point `g8` or `sbt new` command using ssh url to the private remote repository. However `git clone` works properly

**Comment by johnnycaol** [comment]
I have the same problem when try to use `g8` (version 0.11.0) or `sbt new` (sbt version 1.2.8) command to create a template from a private remote repository. It asks for username and password, but never worked even though the username and password are correct. Shouldn't it use ssh config instead by default?

**Comment by devstuff** [comment]
If you've enabled 2FA on your account you'll need to create a personal access token and use that token's value instead of a password.

**Comment by TonioGela** [comment]
@CedricAgoda and @devstuff, can you please test [this fix](https://github.com/foundweekends/giter8/pull/583)? Instructions are provided, and you just need coursier and sbt to build it.
