### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by TheNickWilson** [foundweekends/giter8#335]
Now that conditionals have been added, could you cut a new release?  The extra flexibility it gives us is very powerful and would be mega useful for some templates I'm currently working on.

**Comment by nrinaudo** [comment]
Seconded. They would make some of my work _so_ much easier. Happy to help if there's anything I can do

**Comment by eed3si9n** [comment]
Done. https://github.com/foundweekends/giter8/releases/tag/v0.10.0

**Comment by TheNickWilson** [comment]
Fantastic, much appreciated @eed3si9n !
