### ISSUE TITLE
Generation fails if the generated application's gitignore file contains the entry tmp

### ISSUE THREAD

**Issue by gaelrenoux** [foundweekends/giter8#337]
It does not ask for parameters, directly gives a message "Template applied in /home/grenoux/tmp", and nothing was generated.

I'm using g8 0.9.0. Generation works if you use tmp/** instead of tmp.

I've prepared [a repository](https://github.com/gaelrenoux/giter8-tmp-in-gitignore.g8). The branch 'not-working' contains the failing .gitignore, and the branch 'working' contains a working .gitignore with 'tmp/**'. To reproduce:
`g8 -b not-working gaelrenoux/giter8-tmp-in-gitignore.g8`

**Comment by gaelrenoux** [comment]
By the way, placing .gitignore in the verbatim list has absolutely no effect.

**Comment by TonioGela** [comment]
@gaelrenoux, years have passed, but your repo still exists, and I've been able to test giter8 with both branches using version `0.13.1`. Now the template resolution works flawlessly in both branches and the issue you described a long time ago is occurring no more. For this reason, I'm closing this issue. Sorry for the colossal delay and thanks for reporting.
