### ISSUE TITLE
Verbatim Format

### ISSUE THREAD

**Issue by wolfendale** [foundweekends/giter8#339]
Verbatim mode uses a custom format/implementation for specifying which files should be rendered. It would be fairly straight forward to use the same JGit parsing for ignore files which would mean one common glob format across the tool.

Also, despite the intentions of #324, I believe that the rules should be applied on file paths _relative to the project root_ this will help alleviate inconsistencies between OSes and setups on different machines. In fact, I believe that this is what #324 means given the [tests](https://github.com/foundweekends/giter8/blob/master/library/src/test/scala/giter8/VerbatimTest.scala#L10-L21) are written with paths which look relative to the project root.

Happy to provide a PR if there's general agreement.

**Comment by eed3si9n** [comment]
I am 100% on board adopting `.gitignore` semantics as documented in https://git-scm.com/docs/gitignore.
