### ISSUE TITLE
No 'scala-library*.jar' in Scala compiler classpath in Scala SDK SBT

### ISSUE THREAD

**Issue by ghost** [foundweekends/giter8#349]
Hi all   

Create my project with giter8 as following:  

    sbt new http4s/http4s.g8 -b 0.18  

Then open with IntelliJ and try to run it:  

![screenshot from 2017-11-04 21-39-53](https://user-images.githubusercontent.com/701611/32409451-5051b268-c1ac-11e7-889a-10b3105ed14c.png)

As you can see, I've got an error message.  

My IntelliJ version:  

IntelliJ IDEA 2017.2.5
Build #IU-172.4343.14, built on September 26, 2017  

What am I doing wrong?  

Thanks

**Comment by TonioGela** [comment]
User was deleted
