### ISSUE TITLE
Tests not executed with sbt 1.1.1

### ISSUE THREAD

**Issue by Semptic** [foundweekends/giter8#371]
On version 0.11.0-M3 with sbt 1.1.1 the tests are not executed.

How to reproduce?
* checkout https://github.com/scala/scala-seed.g8
* change sbt version to 1.1.1 
* update the sbt-giter8 version to 0.11.0-M3 
(* Change Hello.scala so that compilation will fail)
* run `sbt g8Test`

=> No tests are executed

**Comment by xuwei-k** [comment]
please try `sbt test:g8Test` instead of `sbt g8Test`

**Comment by TonioGela** [comment]
With lhe latest versions of sbt, sbt-giter8 that come from the scala-seed template, and both `sbt g8Test` and `sbt test:g8Test` are correctly running `root/scripted` tests. @Semptic, can you confirm that?

**Comment by eed3si9n** [comment]
Closing this preemptively.

**Comment by reminia** [comment]
Test / g8Test still doesn't execute the test script.
It needs to run Test / g8 first to produce the test project and then Test / g8Test works.
Look at the source [code](https://github.com/foundweekends/giter8/blob/2fbea86cd283d856722e9f6236ff90408570c227/plugin/src/main/scala/Giter8Plugin.scala#L107),  g8Test task only execute scripts, no dependent relationship on the g8 task.
