### ISSUE TITLE
Allow resolve a template from a sub-directory

### ISSUE THREAD

**Issue by cchantep** [foundweekends/giter8#373]
Either locally or from a sub-directory in a Git repo, to make it possible having multiple (related) templates in the same repo.

**Comment by ches** [comment]
See #396 

Locally, it's possible to do e.g. `sbt new file://path/to/a/template`

**Comment by TonioGela** [comment]
Isn't this actually implemented [here](https://github.com/foundweekends/giter8/blob/3c90ebedbf63be384a8673c11178c53767d85617/cli-git/src/main/scala/Runner.scala#L89-L91) @eed3si9n?

**Comment by eed3si9n** [comment]
I guess so. I'm closing this for now, but let us know if `--directory` doesn't address it.
