### ISSUE TITLE
Doc: Add command arguments to the documentation

### ISSUE THREAD

**Issue by jiminhsieh** [foundweekends/giter8#396]
Maybe we could add a documentation about command arguments at this page - [Usage](http://www.foundweekends.org/giter8/usage.html).
https://github.com/foundweekends/giter8/blob/df63ff633c4025df72bc873d454a876fb1d4b395/app/src/main/scala/giter8.scala#L66-L84

**Comment by ches** [comment]
Agree, especially since [the `sbt new` documentation says this][1]:

> ### Giter8 parameters 

> You can append Giter8 parameters to the end of the command, so for example to specify a particular branch you can use:

>     $ sbt new scala/scala-seed.g8 --branch myBranch

And yet, you can't find mention of such parameters anywhere in Giter8 docs.

[1]: https://www.scala-sbt.org/1.x/docs/sbt-new-and-Templates.html#Giter8+parameters
