### ISSUE TITLE
Find the latest scala version

### ISSUE THREAD

**Issue by raboof** [foundweekends/giter8#405]
Similar to http://www.foundweekends.org/giter8/template.html#Maven+properties, it would be cool if we could automatically find the latest Scala version in a tree, e.g. `scala(2.12)` (currently) producing `2.12.7`. Or is there some way to achieve this already?

**Comment by anilkumarmyla** [comment]
this works for me

default.properties
`scala_version = maven(org.scala-lang, scala-library, stable)`

build.sbt
scalaVersion := "$scala_version$"

**Comment by mkurz** [comment]
Also
```
scala_version = maven(org.scala-lang, scala-library, stable)
```
works for us since many years.

I think this can be closed.

**Comment by raboof** [comment]
lol I've been using that for ages as well, completely forgot about (closing) this issue ;)
