### ISSUE TITLE
'" % "' a complete surprise

### ISSUE THREAD

**Issue by jpsacha** [foundweekends/giter8#436]
Getting error `'" % "' came as a complete surprise to me` when processing third line of the following code:

```scala
lazy val javaFXModules = Seq("base", "controls", "fxml")
libraryDependencies ++= javaFXModules.map( m=>
  "org.openjfx" % s"javafx-$m" % "12.0.2" classifier osName
)
```

I tried to rewrite escaping with `\`. Did not work. I tried to rewrite the code without using `%`:
```scala
lazy val javaFXModules = Seq("base", "controls", "fxml")
libraryDependencies ++= javaFXModules.map( m=>
  ModuleID("org.openjfx", s"javafx-$m", "12.0.2") classifier osName
)
```
this time got error  `'" , "' came as a complete surprise to me`.
Maybe this is an issue with the parsing the lambda `m => ...`?

The complete code is in repo: https://github.com/jpsacha/scalafx.g8/tree/complete_surprise on branch `complete_surprise`

**Comment by eed3si9n** [comment]
I haven't tried on your template, but usually you have to escape `$` with `\$`.

**Comment by jpsacha** [comment]
@eed3si9n you are right. I got confused with the message about `%`, it was pointing to wrong character, after escaping `$` it works fine.

**Comment by eed3si9n** [comment]
closing this then.
