### ISSUE TITLE
Release on homebrew?

### ISSUE THREAD

**Issue by anilkumarmyla** [foundweekends/giter8#446]
0.12.0 is not released on homebrew yet cc @eed3si9n 

the last one https://github.com/Homebrew/homebrew-core/pull/30156

**Comment by rkrdo** [comment]
I opened https://github.com/Homebrew/homebrew-core/pull/50138, but I'm not sure what else needs to be done

**Comment by eed3si9n** [comment]
https://github.com/Homebrew/homebrew-core/pull/50138#issuecomment-586066199

I now publish the bootstrap Bash script to Maven Central as https://repo1.maven.org/maven2/org/foundweekends/giter8/giter8-bootstrap_2.12/0.12.0/giter8-bootstrap_2.12-0.12.0.sh. Homebrew needs to switch to downloading that as `g8`.

**Comment by rkrdo** [comment]
So does the whole formula need to change @eed3si9n ?

I was able to install giter8 successfully via `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/e862e0c23500b32fcab5b80729747be988144c08/Formula/giter8.rb`

**Comment by eed3si9n** [comment]
Yea. Here's my PR - https://github.com/Homebrew/homebrew-core/pull/50160
