### ISSUE TITLE
Installation with JDK11 does not work

### ISSUE THREAD

**Issue by sebastiankirsch** [foundweekends/giter8#449]
## steps

I'm executing

    wget -q https://raw.githubusercontent.com/foundweekends/conscript/master/setup.sh -O- | sh
    ~/.conscript/bin/cs foundweekends/giter8

## problem

While the first command works, the second one fails with:
```WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.netty.util.internal.ByteBufferUtil (file:/home/skirsch/.conscript/boot/scala-2.11.12/org.foundweekends.conscript/conscript/0.5.3/netty-3.9.2.Final.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.jboss.netty.util.internal.ByteBufferUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
An unexpected error occurred: Please check your internet connection.
Exception message: https://api.github.com/repos/foundweekends/giter8/git/refs/heads/master
```

<details>

<summary>stack trace</summary>

```scala
there is none
```

</details>

## expectation

The installation should have worked!

## notes
Installation with JDK8 works:
```
me@workstation:~/develop/is24-java-backend-template$ sudo update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
* 2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode
```
However, we want to use giter8 on a Jenkins build agent that is only equipped with JDK11.

**Comment by ugurkoysuren** [comment]
Same here, 
trying to execute  cs foundweekends/giter8

Environments:
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04)

**Comment by flyingFish2020** [comment]
Any word on this?
![conscript_error](https://user-images.githubusercontent.com/59601087/85916527-edd14c80-b851-11ea-8ab1-2480f98e790f.png)

**Comment by sebastiankirsch** [comment]
> This is due to the Netty version (currently 3.9.2 if I'm correct). Netty must be updated to a version >= 4.1.30 ([netty/netty#8318](https://github.com/netty/netty/issues/8318))

This seems to be coming via https://github.com/foundweekends/conscript/blob/master/project/Dependencies.scala#L6
The ´dispatch-core´ version is really outdated, referring to an old version of `async-http-client`, which in turn is using a likewise outdated Netty.version.

`org.asynchttpclient:async-http-client-project` needs to be at a minimum of 2.5.3, yet the most recent version of `dispatch-core` uses version 2.0.39. I've no SBT experience, so I don't know how to manage the version (Maven's dependencyManagement equivalent). And god knows if it still builds/runs then...

**Comment by sebastiankirsch** [comment]
Ah, I've been mislead. While this may be a problem with JDK17+, the issued warning may have nothing to do with the error.

**Comment by TonioGela** [comment]
@sebastiankirsch can you try using the updated [Setup](http://www.foundweekends.org/giter8/setup.html) page instructions that rely on coursier?

**Comment by sebastiankirsch** [comment]
@TonioGela I'm afraid we've transitioned to https://github.com/tenpureto/tenpureto in the meantime.

**Comment by TonioGela** [comment]
No worries @sebastiankirsch.
Btw, I tested it with [openjdk docker images](https://hub.docker.com/_/openjdk), in particular I used 8, 11 and 17 
```bash
docker run -it --rm openjdk:{8,11,17} /bin/bash
# And then in each running container
curl -fLo cs https://git.io/coursier-cli-"$(uname | tr LD ld)"
chmod +x cs
./cs install giter8
export PATH="$PATH:/root/.local/share/coursier/bin"
g8 --version
```
In each of the 3, I get `g8 0.13.1` as output.
I'm closing it since the actually documented installation instructions are correctly working, feel free to reopen it in case of troubles.
