### ISSUE TITLE
Document new launcher

### ISSUE THREAD

**Issue by eed3si9n** [foundweekends/giter8#454]
New 0.12.0 bootstrap is published to Maven Central.

```sh
curl http://repo1.maven.org/maven2/org/foundweekends/giter8/giter8-bootstrap_2.12/0.12.0/giter8-bootstrap_2.12-0.12.0.sh > ~/bin/g8
```

**Comment by ekrich** [comment]
This is far better than the `conscript` setup.

**Comment by TonioGela** [comment]
@eed3si9n I think this can be closed too. However it doesn't seem to me that the doc on gh pages was updated, am I wrong?
