### ISSUE TITLE
Confused by shell syntax, write template or document / add escaping feature.

### ISSUE THREAD

**Issue by drocsid** [foundweekends/giter8#466]
## steps

```sbt new drocsid/http4s.g8 -b feature/shell-script```

or

```
git clone https://github.com/drocsid/http4s.g8
git checkout feature/shell-script
g8 file://path_to_repo_on_branch_feature/shell-script
```

sbt or Giter8 version: `sbt 1.3.10` or `g8 12.0`

## problem

It seems that the giter8 template is confused by my use of shell conditional syntax. In this case I'm also using giter8 template conditionals.  Triggering the template should just write the shell script, or perhaps there should be an escape pattern feature mentioned in the documentation.

https://github.com/drocsid/http4s.g8/blob/a233f6c3e7a7fcd3e752f6a8faf185c82e0bacb6/src/main/g8/%24if(graal_native_image.truthy)%24build-native-image.sh%24endif%24#L4

<details>
`sbt new drocsid/http4s.g8 -b feature/shell-script`

```
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from /home/colin/.sbt/1.0/plugins
[info] Set current project to tmp (in build file:/tmp/)
[info] Set current project to tmp (in build file:/tmp/)
name [quickstart]: 
organization [com.example]: 
package [com.example.quickstart]: 
scala_version [2.13.1]: 
sbt_version [1.3.10]: 
http4s_version [0.21.3]: 
circe_version [0.13.0]: 
logback_version [1.2.3]: 
specs2_version [4.9.3]: 
graal_native_image [TRUE/false]: 
is_linux_build [false ]: 
scala_assembly_target [scala-2.13]: 
```

<summary>stack trace</summary>

```scala
Exiting due to error in the template: /tmp/giter8-2015167789015
File: /tmp/giter8-2015167789015/src/main/g8/$if(graal_native_image.truthy)$build-native-image.sh$endif$, 4:14: '=' came as a complete surprise to me
```

</details>

## expectation

Shell script should be written.

**Comment by izharahmd** [comment]
@drocsid https://github.com/foundweekends/giter8/issues/102#issuecomment-357480127

**Comment by TonioGela** [comment]
@drocsid I pulled your fork and I escaped `OSTYPE` and `STATIC` variables and added the shebang and quoted `STATIC` as [shellcheck](shellcheck.net) suggested. It worked flawlessly. 
```bash
#!/bin/bash
#You can build a native-image binary as mentioned in the http4s deployment [section] (https://github.com/drocsid/http4s/blob/docs/deployment/docs/src/main/tut/deployment.md) . You will need to follow the directions there to provide GraalVM / native-image plugin and provide a muslC bundle. Then populate the UseMuslC path with it's location.

if [[ \$OSTYPE == linux-gnu ]]; then STATIC='--static -H:UseMuslC="/path.to/muslC"'; fi

native-image "\$STATIC" -H:+ReportExceptionStackTraces -H:+AddAllCharsets --allow-incomplete-classpath --no-fallback --initialize-at-build-time --enable-http --enable-https --enable-all-security-services --verbose -jar "./target/$scala_assembly_target$/$name$-assembly-0.0.1-SNAPSHOT.jar" $name$BinaryImage
```
Please refer to [documentation](http://www.foundweekends.org/giter8/template.html#default.properties) where it says `Dollar signs can be escaped to avoid resolution`.

**Comment by TonioGela** [comment]
@drocsid I've [opened a PR](https://github.com/drocsid/http4s.g8/pull/3) to fix issues on your fork and I'm closing the issue, feel free to reopen it if needed.
