### ISSUE TITLE
Goodbyte Travis CI

### ISSUE THREAD

**Issue by xuwei-k** [foundweekends/giter8#489]
- https://travis-ci.com/organizations/foundweekends/plan
- https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

use GitHub Actions or another CI service? 🤔 

![plan](https://user-images.githubusercontent.com/389787/99840509-0733b600-2bb0-11eb-8583-e357c36e0711.png)

**Comment by eed3si9n** [comment]
+1 on GitHub Actions
