### ISSUE TITLE
Is there a way to generate the files and directories in a specified folder?

### ISSUE THREAD

**Issue by iamsmkr** [foundweekends/giter8#504]
I was wondering if there is way we can specify an output directory for the g8 command to unwrap the template into?

**For Example**,
```
g8 unfiltered/unfiltered.g8 --out=/home/mypreferreddirectory
```

This should create all the files and directories into `/home/mypreferreddirectory` location.

**Comment by TonioGela** [comment]
One of the command line arguments is `-o` or `--out` and accepts a path that overrides the destination directory. When #574 will get merged, the documentation on site will contain details about it.
