### ISSUE TITLE
g8.bat is not able to download templates on a Windows PC

### ISSUE THREAD

**Issue by smartiniOnGitHub** [foundweekends/giter8#54]
Hi,
on a Windows PC I have installed conscript, then n8han/giter8 via cs command.

Anytime I try to use g8 to download a template (like the folowing) I get this:

```
g8 typesafehub/scala-sbt

Exception fetching from github org/apache/http/HttpRequest
```

of course my network connection is working and the related URL is accessible for me, and I'm not using an HTTP Pproxy.

The strange thing is that on this PC I have the same problem even using g8 from typesafe-2.0.1 universal installer zip (the related ticket there is this: https://github.com/typesafehub/giter8-package/issues/5 ):

I'm using JDK 6 Update 30, on Windows Server 2003 R2, and the Windows Firewall is disabled.
Note that on this machine I'm using a lot of other Java dev tools that download things from Internet (other installations of sbt, Grails, Play, etc) ... just for info.

I just tried to refresh security settings under my user profile folder and even in the work folder, but nothing changes.

Important: doing the same but from other PC (one with Windows 7, another with Windows XP) and all works good (both in "standard" g8, and even in typesafe bundled g8. So, to try to better understand this, how could I enable an higher log/debug info in g8 ?

Thank you very much, 
Sandro

**Comment by eed3si9n** [comment]
Is this still a problem on the latest giter8?
