### ISSUE TITLE
Conscript fails to install giter8 on MacOS

### ISSUE THREAD

**Issue by jasperstein** [foundweekends/giter8#545]
## steps

Trying to install giter8 locally using conscript (since `brew` no longer will, see also https://github.com/foundweekends/giter8/issues/475).

MacOS 11.2.3, conscript 0.5.5, sbt 1.5.0.

## problem

giter8 won't download, let alone install.

<details>

<summary>stack trace</summary>

```zsh
% cs foundweekends/giter8
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.netty.util.internal.ByteBufferUtil (file:/Users/jasperstein/.conscript/boot/scala-2.11.12/org.foundweekends.conscript/conscript/0.5.5/netty-3.9.2.Final.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.jboss.netty.util.internal.ByteBufferUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
An unexpected error occurred: Please check your internet connection.
Exception message: https://api.github.com/repos/foundweekends/giter8/git/refs/heads/master
```

</details>

## expectation

giter8 is installed

**Comment by TonioGela** [comment]
Have you tried [Coursier](https://get-coursier.io/)? It is possible to install g8 simply prompting `cs install giter8`.

**Comment by fmv1992** [comment]
I'm running into the same problem on Ubuntu. `cs install giter8` does not work neither.

**Comment by TonioGela** [comment]
Which java version are you using?

**Comment by TonioGela** [comment]
Are you using conscript or coursier?

**Comment by TonioGela** [comment]
Just to be sure, try installing coursier locally and not globally using
```
curl -fLo cs https://git.io/coursier-cli-"$(uname | tr LD ld)"
chmod +x cs
```
and then try installing giter8 with it `./cs install giter8`
If it works you might consider installing it globally using the one you just downloaded 
```
./cs install cs
rm cs
```
but remember to uninstall conscript first

**Comment by fmv1992** [comment]
Thanks, that worked for me!

**Comment by TonioGela** [comment]
You're welcome! @jasperstein what about you?

**Comment by jasperstein** [comment]
It does 👍 Thanks!

However the official documentation at http://www.foundweekends.org/giter8/setup.html only mentions brew and conscript, both of which do _not_ work. (So this is more a documentation issue than anything else)

**Comment by TonioGela** [comment]
I will update it ASAP, don't worry.

**Comment by TonioGela** [comment]
@jasperstein documentation is now updated
