### ISSUE TITLE
Github Pages doesn't get updated

### ISSUE THREAD

**Issue by TonioGela** [foundweekends/giter8#569]
Despite in the last weeks, I've updated the documentation on some points, and the changes were merged. This wasn't reflected on Github Pages.
I think this can be caused by [this condition](https://github.com/foundweekends/giter8/blob/develop/.github/workflows/ci.yml#L71) in the `ci.yml` file and the fact that a `master` branch doesn't exist anymore. I can open a PR to modify `refs/heads/master` to `refs/heads/develop`, but I'm not sure that this is the intended behaviour since you might want documentation updated just on releases.
By the way, the recent documentation changes were done to document the **actual** behaviour of `giter8`.
What do you think @eed3si9n and @xuwei-k?

[EDIT] The reason I'm pushing is that with that doc changes (and others that I'm about to do) some issues on the project can be closed since they are documentation related.

**Comment by eed3si9n** [comment]
I think doc should be updated on merge. s/master/develop/ is fine for now.

**Comment by TonioGela** [comment]
Opened #571 for that so.

**Comment by TonioGela** [comment]
Hmm, despite https://github.com/foundweekends/giter8/runs/2700879772?check_suite_focus=true the [Setup](http://www.foundweekends.org/giter8/setup.html) page doesn't seem aligned to [docs/01.md](https://github.com/foundweekends/giter8/blob/develop/docs/01.md) what are we missing?

**Comment by xuwei-k** [comment]
😭 

https://github.com/foundweekends/giter8/blob/5d6b1a4eb63fd78fff11bfb6d0f1864cfb0e79ef/project/TravisSitePlugin.scala#L77-L85

**Comment by TonioGela** [comment]
Okay, technically if we commit a newline in any markdown in docs we should get the new documentation. Right?
