### ISSUE TITLE
Incorrect line-breaks in description property with manual line-breaks

### ISSUE THREAD

**Issue by arteme** [foundweekends/giter8#596]
## steps

Giter8 version: 0.13.1 (https://repo1.maven.org/maven2/org/foundweekends/giter8/giter8-bootstrap_2.12/0.13.1/giter8-bootstrap_2.12-0.13.1.sh)

## problem

When using a multi-line description property with manually specified line-breaks it seems that the general line-break formatting is applied before manual line-breaks are taken into account.

<details>

<summary>default.properties file</summary>

```
description = \
  Create a new project.\n\
  Use naming convention like '<this> <that> project'\n\
  (e.g. 'Hello World project')\n\
  Project folder and SBT project name will be normalized with hyphens. 

name = Shiny New project
scala_version = 2.12.13
```

</details>

## expectation

When the description is printed to the terminal I would expect the manual line-breaks to be applied first and then any long lines that exceed the width limit set by g8 to be split into multiple lines.

## reality

Instead, it seems like the text is broken into lines based on the g8 width limit before manual line-breaks are taken into account resulting in the following;

```
$ g8 file://shiny-new-template.g8
log4j:ERROR A "org.apache.log4j.ConsoleAppender" object is not assignable to a "org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by 
log4j:ERROR [java.net.URLClassLoader@74a10858] whereas object of type 
log4j:ERROR "org.apache.log4j.ConsoleAppender" was loaded by [java.net.URLClassLoader@5b480cf9].
log4j:ERROR Could not instantiate appender named "stderr".

Create a new project.
Use naming convention like '<this> <that> 
project'
(e.g. 'Hello World project')
Project folder and SBT project 
name will be normalized with hyphens. 

name [Shiny New project]: 
```

**Comment by eugeniyk** [comment]
@arteme please take a look in #622 whether this is what you're aiming for?
