### ISSUE TITLE
Backstage + giter8

### ISSUE THREAD

**Issue by MPV** [foundweekends/giter8#664]
Anyone here who's looked at Backstage and their software templates?
https://backstage.io/docs/features/software-templates/software-templates-index

We're looking at project generation and whether to use giter8, Backstage, or both.
I'm curious if/how they could be combined, and/or how they compare.

**Comment by eed3si9n** [comment]
I am not familiar with Backstage. It says it's a platform for building developer portal, which has software template feature as well? Giter8 just does software template.

Also Backstage seems to use web UI to use the templates, and targets apps that is managed inside Backstage? (I am not sure)

Giter8 templates are often consumed using `g8` or via `sbt new`, and the resulting apps are in a directories on your laptop.

**Comment by eed3si9n** [comment]
Closing this out for now.
