### ISSUE TITLE
verbatim ignored?

### ISSUE THREAD

**Issue by mads-hartmann** [foundweekends/giter8#69]
Hi, 

As I understand it you can use the `verbatim` field in the `default.properties` file to tell giter8 to not parse but just copy some files. I have 

```
verbatim=*.html *.js *.css
```

But when I run `g8` it still asks the user for input on the verbatim key: 

```
g8 file:///Users/mads379/dev/projects/lift.g8

Template for creating Lift projects 

package [com.code]: 
name [My New Lift Project]: ll
verbatim [*.html *.js *.css]: 
lift_version [2.5-SNAPSHOT]: 
```

I don't want the user to have any say in what templates should be parsed or not. Is this the expected behaviour?

**Comment by felipe-vieira0** [comment]
How do I include a file unconditionally?
