### ISSUE TITLE
Unhyphenate

### ISSUE THREAD

**Issue by manuelbernhardt** [foundweekends/giter8#74]
Based on a lowercase hyphen'd key such as `my-nice-project` I'd like to generate:
- myNiceProject
- MyNiceProject
- my nice project
- ...

I guess that a hyphen to whitespace transformation would do the trick here?

**Comment by janjaali** [comment]
Just for those who stumble upon this issue, the ['space'](https://github.com/foundweekends/giter8/blob/dd74501191190df5554d03437f8de601ca13f6dc/library/src/main/scala/g8.scala#L228) format is the one the original reporter was looking for here ;)

**Comment by TonioGela** [comment]
> Just for those who stumble upon this issue, the ['space'](https://github.com/foundweekends/giter8/blob/dd74501191190df5554d03437f8de601ca13f6dc/library/src/main/scala/g8.scala#L228) format is the one the original reporter was looking for here ;)

Exactly, in particular given `foo="my-nice-project"`:
- `myNiceProject` can be obtained with `$foo;format="space,start,word,decap"$`
- `myNiceProject` can be obtained with `$foo;format="space,start,word"$`
- `my nice project` can be obtained with `$foo;format="space"$`

I just tested these expressions locally using `0.13.1` as the ugly screenshots are testifying:

![image](https://user-images.githubusercontent.com/41690956/118858989-015a2b80-b8da-11eb-8f26-01fa1a7d8a53.png)
![image](https://user-images.githubusercontent.com/41690956/118859019-0b7c2a00-b8da-11eb-9c42-106214d40ec1.png)

Given all of this, isn't this issue closable @eed3si9n ?

**Comment by TonioGela** [comment]
FYI if anybody thinks these expressions are worth documenting I can open a PR to add them to documentation.

**Comment by eed3si9n** [comment]
ok. closing this then.
