### ISSUE TITLE
A new release

### ISSUE THREAD

**Issue by eed3si9n** [foundweekends/giter8#786]
Any chance for a new release soon? Thanks!

_Originally posted by @mkurz in https://github.com/foundweekends/giter8/issues/771#issuecomment-1530054506_

**Comment by eed3si9n** [comment]
It would be good to make a release prior to sbt 1.9.0.

**Comment by eed3si9n** [comment]
https://github.com/foundweekends/giter8/releases/tag/v0.16.2

**Comment by mkurz** [comment]
Thanks!
