### ISSUE TITLE
Recent version/s seem to remove executable flag from files

### ISSUE THREAD

**Issue by ymasory** [foundweekends/giter8#90]
For example:

``` sh
g8 scalatra/scalatra-sbt
```

The `sbt` start script in root lacks executable permissions, even though the file in the Git repo has executable perms.
This seems to be a regression, since previous versions of g8 kept the executable perm.
It's not the end of the world, but it does add a post-install step (`chmod u+x sbt`) that could otherwise be avoided.

Thanks for all your g8 work!

**Comment by rafael** [comment]
I'm still having this issue when applying g8 from a local repo `g8 file://scalatra-sbt.g8 `. Could it be that the patch needs to be applied in another place as well? The permissions seem to be set correctly when I use it like this:

```
g8 scalatra/scalatra-sbt 
````

**Comment by rafael** [comment]
Also, it looks like it's respecting the permissions fully. I have a file like this in the template:

```
-rwxr-xr-x  1 user 
```

and it gets copied over like this:

```
-rwxr--r--  1 user
```
