### ISSUE TITLE
How can I skip webp file from giter8 parsing?

### ISSUE THREAD

**Issue by zaryabRiasat** [foundweekends/giter8#921]
I'm creating custom template using giter8. The problem is when I run `sbt new file://custom-template.g8`, it gives me error on **.jar** file as well as **.webp** files. I want the giter8 to not parse these files but to add these files in newly created project using this template.

I've tried to put these in **.g8ignore** file but it is completely ignoring these, and not adding these files in newly created project. My **.g8ignore** file looks like:
```
**/*.jar
**/*.webp
```

Is there any method to make giter8 to not parse these files, but include it in project?

**Comment by eed3si9n** [comment]
Could you try

```
verbatim = *.jar *.webp
```

https://www.foundweekends.org/giter8/template.html#verbatim+field

**Comment by zaryabRiasat** [comment]
@eed3si9n It worked for me. I appreciate that. Thanks.
