### ISSUE TITLE
Can't use property description

### ISSUE THREAD

**Issue by marceloemanoel** [foundweekends/giter8#99]
It seems that the property `description` has a special meaning to giter8 however I can't use it on my templates as I can with `package` or `name` properties.

**Comment by jrduncans** [comment]
The logic that treats this is special also does not seem to be triggered when you run `sbt g8Test` or the like, since it bypasses prompting. If description is going to be reserved, it would be nice if it was documented and implemented everywhere consistently.

**Comment by TonioGela** [comment]
Fixed in #572. Can be closed.
